version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      wrk:
        patterns: [ "*" ]
  - package-ecosystem: "gomod"
    directory: "/grpc"
    schedule:
      interval: "weekly"
    groups:
      wrk|grpc:
        patterns: [ "*" ]
